// todo/src/app/list-todos/list-todos.component.ts
import { Component, OnInit } from '@angular/core';
import {WelcomeComponent} from '../welcome/welcome.component';

export class Todo {

  constructor(
    public id: number,
    public description: string,
    public done: boolean,
    public targetDate: Date
  ) { }

}



@Component({
  selector: 'app-list-todos',
  templateUrl: './list-todos.component.html',
  styleUrls: ['./list-todos.component.css']
})
export class ListTodosComponent implements OnInit {

  todos = [
    new Todo(1, 'Learn to Dance', false, new Date()),
    new Todo(2, 'Become expert in Angular', false, new Date()),
    new Todo(3, 'Become java Expert', false, new Date())
  ]


  constructor() { }

  ngOnInit() {
  }

}

<h1>My Todo's</h1>
<div class="container">
        <table class="table">
                <caption>My ToDo's</caption>
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>Target Date</th>
                        <th>Is completed?</th>
                    </tr>
            
                </thead>
            
                <tbody>
            
                    <!-- for (Todo todo:todos) -->
                    <tr *ngFor="let todo of todos">
                        <td>{{todo.description}}</td>
                        <td>{{todo.targetDate | date | uppercase}}</td>
                        <td>{{todo.done}}</td>
                    </tr>
            
                </tbody>
            
            </table>


</div>

// todo-app/src/components/todo/ListTodosComponent.jsx
import React, { Component } from 'react'


class ListTodosComponent extends Component {

    constructor(props) {
        super(props)
        this.state = {
            todos: [
                { id: 1, description: 'Learn React', done: false, targetDate: new Date() },
                { id: 2, description: 'Visit Spit in Himachal', done: false, targetDate: new Date() },
                { id: 3, description: 'Learn Java 8', done: false, targetDate: new Date() }
            ]
        }

    }

    render() {
        return (
            <div>
                <h1>List Todos</h1>
                <div className="container">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th>Target Date</th>
                                <th>IsCompleted?</th>
                            </tr>
                        </thead>
                        <tbody>
                            {
                                this.state.todos.map(
                                    todo =>
                                        <tr key={todo.id}>
                                            <td>{todo.description}</td>
                                            <td>{todo.done.toString()}</td>
                                            <td>{todo.targetDate.toString()}</td>
                                        </tr>
                                )
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        )
    }
}

export default ListTodosComponent;
