// todo-app/src/components/todo/WelcomeComponent.jsx
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import HelloWorldService from '../../api/todo/HelloWorldService'
class WelcomeComponent extends Component {

    constructor(props){
        super(props)
        this.retrievemessage = this.retrievemessage.bind(this)
        this.handleSuccessfulResponse = this.handleSuccessfulResponse.bind(this)
        this.state = {
            message:''
        }
    }
    render() {
        return (
            <>
                <h1>Welcome!</h1>
                <div className="container">

                    Welcome {this.props.match.params.name}. You can manage todos <Link to="/todos">here</Link>.
                {/* To avoid entire page refresh we are using Link tag */}

                </div>
                <div className="container">

               Click here to get customised welcome message <button className="btn btn-success" onClick={this.retrievemessage}>Get Welcome Message</button>

                </div>
                <div className="container">
                    {this.state.message}
                </div>
            </>
        )
    }

    retrievemessage(){
        HelloWorldService.executeHelloWorldPathService(this.props.match.params.name)
        .then(response => this.handleSuccessfulResponse(response))
        //.catch()
    }

    handleSuccessfulResponse(response) {
        this.setState(
            { message: response.data.message }
        )
    }
}
export default WelcomeComponent

// todo/src/app/welcome/welcome.component.ts
import { Component, OnInit } from '@angular/core';
import { AppComponent } from '../app.component';
import { ActivatedRoute } from '@angular/router';
import { WelcomeDataService } from '../service/data/welcome-data.service';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
//by using export keyword this class can be used outside of this file ( or the module)
export class WelcomeComponent implements OnInit {
 
  message = 'Some welcome message'
  param = ''
  //keyword constructor used to define constructor
  //We are using ActivateRoute
  constructor(private route: ActivatedRoute, private service:WelcomeDataService) {

  }

  //quite similar to void ngOnInit()
  ngOnInit() {    
    this.param = this.route.snapshot.params['name']
  }

  getWelcomeMessage(){
    console.log(this.service.executeHelloWorldBeanService());
    this.service.executeHelloWorldBeanService().subscribe(
      response => console.log(response.message)
    );

    console.log('getWelcome() ends')
    
  }

  handleSuccessfulResponse(response){
    console.log(response);
  }

}
//In javascript one module represent one file, and one file contains multiple functions and classes
<div class="container">
        
        Welcome {{param}} to our Awesome App!
        You can manage your todos <a routerLink="/todos">here</a>
</div>

<div class="container">
Click here to get customised message 
<button class= ".btn btn-success" (click)="getWelcomeMessage()">Get Welcome Message</button>
</div>
